### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by prithiv0005** [t2k-nd280-upgrade/t2k-nd280-upgrade#12]
Hi, can you please tell me which version of GEANT and ROOT is used. 

I am using 
- geant4_version11  
- root_6.26.00

The code is facing so many errors.

**Comment by suvorov21** [comment]
Hi!

I've just ensured that it works well with ROOT 6.20.04 and GEANT 10.05.p01

I imagine that the ROOT version is not critical, but the G4 version is. As some classes were modified.

**Comment by prithiv0005** [comment]
> Hi!
> 
> I've just ensured that it works well with ROOT 6.20.04 and GEANT 10.05.p01
> 
> I imagine that the ROOT version is not critical, but the G4 version is. As some classes were modified.

Thanks for the help. I will contact you if I need further assistance :).

**Comment by prithiv0005** [comment]
Hi, can you also help me with this issue @suvorov21? I have tried to use the **make** command after making the **build_dir** folder in the src directory. I am getting this issue.

**The error is**
prithivraj@prithiv:~/t2k-nd280-upgrade-master/src/build_dir$ make
app/nd280UpEvent/CMakeFiles/ND280Event.dir/build.make:330: *** target pattern contains no '%'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:139: app/nd280UpEvent/CMakeFiles/ND280Event.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
