### ISSUE TITLE
Make file error

### ISSUE THREAD

**Issue by prithiv0005** [t2k-nd280-upgrade/t2k-nd280-upgrade#13]
Hi, can you also help me with this issue @suvorov21? I have tried to use the **make** command after making the **build_dir folder** in the src directory. I am getting this issue.

**The error is**
prithivraj@prithiv:~/t2k-nd280-upgrade-master/src/build_dir$ make
app/nd280UpEvent/CMakeFiles/ND280Event.dir/build.make:330: *** target pattern contains no '%'. Stop.
make[1]: *** [CMakeFiles/Makefile2:139: app/nd280UpEvent/CMakeFiles/ND280Event.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by suvorov21** [comment]
Did CMake finish w/o any errors?

**Comment by prithiv0005** [comment]
> Did CMake finish w/o any errors?

Yes, CMake worked w/o any errors.

**Comment by suvorov21** [comment]
In this case I have no idea what can went wrong. CMake it responsible for creating Makefile. We don't modify them by hand. So if it's a problem in Makefile that is CMake who did it. And I would expect to see an error in CMake in case anything went wrong there.

**Comment by prithiv0005** [comment]
> In this case I have no idea what can went wrong. CMake it responsible for creating Makefile. We don't modify them by hand. So if it's a problem in Makefile that is CMake who did it. And I would expect to see an error in CMake in case anything went wrong there.

Thank you so much for the update. Can you specify the directory where should I create the **build_dir**? This is for confirmation whether I have done it right or wrong.

**Comment by suvorov21** [comment]
I've tried to make it in the src/ folder and it works fine for me. In general you can put it anywhere. Could you try to create a new folder and then post here the output of the CMake?

**Comment by prithiv0005** [comment]
> I've tried to make it in the src/ folder and it works fine for me. In general you can put it anywhere. Could you try to create a new folder and then post here the output of the CMake?

I think I have found the issue. I think the issue is with the GEANT4, and ROOT directories in the **T2KND280Up_CLHEP.sh** file. 

***************************************************************************
prithivraj@prithiv:~/t2k-nd280-upgrade-master/src/build_dir$ pwd
/home/prithivraj/t2k-nd280-upgrade-master/src/build_dir
***************************************************************************
prithivraj@prithiv:~/t2k-nd280-upgrade-master/src/build_dir$ cmake ..
-- /home/prithivraj/t2k-nd280-upgrade-master/src/../cmake
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
 Looking for Geant4...
GEANT4_INCLUDE_DIRS : /home/prithivraj/geant4/geant4_v10.5/geant4.10.05.p01-install/include/Geant4
GEANT4_LIBRARY_DIR : /home/prithivraj/geant4/geant4_v10.5/geant4.10.05.p01-install/lib/Geant4-10.5.1/Linux-g++
GEANT4_CONFIG_EXECUTABLES : 
-- found in /home/prithivraj/geant4/geant4_v10.5/geant4.10.05.p01-install/include/Geant4

-- libraries : /bin/sh: 1: GEANT4_CONFIG_EXECUTABLE-NOTFOUND: not found
-- flags : /bin/sh: 1: GEANT4_CONFIG_EXECUTABLE-NOTFOUND: not found

-- Geant4 version > 10.02p03 detected. Special flag is added for compilation
-- C flags      : 
-- CXX flags    :  /bin/sh: 1: GEANT4_CONFIG_EXECUTABLE-NOTFOUND: not found -DNEW_G4 -Wno-overloaded-virtual -Wno-shadow -Wno-unused-const-variable
-- Linker flags :  -Wl,--no-as-needed
-- ND280Event ...
-- pbuilder: will build library <ND280Event>
-- EffStudy ...
-- pbuilder: will build library <EffStudy>
-- programs: EffStudyApp
-- project libraries( exe): ND280Event;EffStudy
-- external libraries: /home/prithivraj/root/root-6.20.04-install/lib/libCore.so;/home/prithivraj/root/root-6.20.04-install/lib/libRIO.so;/home/prithivraj/root/root-6.20.04-install/lib/libNet.so;/home/prithivraj/root/root-6.20.04-install/lib/libHist.so;/home/prithivraj/root/root-6.20.04-install/lib/libGraf.so;/home/prithivraj/root/root-6.20.04-install/lib/libGraf3d.so;/home/prithivraj/root/root-6.20.04-install/lib/libGpad.so;/home/prithivraj/root/root-6.20.04-install/lib/libTree.so;/home/prithivraj/root/root-6.20.04-install/lib/libRint.so;/home/prithivraj/root/root-6.20.04-install/lib/libPostscript.so;/home/prithivraj/root/root-6.20.04-install/lib/libMatrix.so;/home/prithivraj/root/root-6.20.04-install/lib/libPhysics.so;/home/prithivraj/root/root-6.20.04-install/lib/libMathCore.so;/home/prithivraj/root/root-6.20.04-install/lib/libThread.so;/home/prithivraj/root/root-6.20.04-install/lib/libMultiProc.so;/home/prithivraj/root/root-6.20.04-install/lib/libRooStats.so;/home/prithivraj/root/root-6.20.04-install/lib/libRooFit.so;/home/prithivraj/root/root-6.20.04-install/lib/libRooFitCore.so;/home/prithivraj/root/root-6.20.04-install/lib/libTreePlayer.so;/home/prithivraj/root/root-6.20.04-install/lib/libGeom.so;/bin/sh: 1: GEANT4_CONFIG_EXECUTABLE-NOTFOUND: not found
-- pbuilder: will build the following executables: EffStudyApp
-- ND280Event;EffStudy /home/prithivraj/root/root-6.20.04-install/lib/libCore.so;/home/prithivraj/root/root-6.20.04-install/lib/libRIO.so;/home/prithivraj/root/root-6.20.04-install/lib/libNet.so;/home/prithivraj/root/root-6.20.04-install/lib/libHist.so;/home/prithivraj/root/root-6.20.04-install/lib/libGraf.so;/home/prithivraj/root/root-6.20.04-install/lib/libGraf3d.so;/home/prithivraj/root/root-6.20.04-install/lib/libGpad.so;/home/prithivraj/root/root-6.20.04-install/lib/libTree.so;/home/prithivraj/root/root-6.20.04-install/lib/libRint.so;/home/prithivraj/root/root-6.20.04-install/lib/libPostscript.so;/home/prithivraj/root/root-6.20.04-install/lib/libMatrix.so;/home/prithivraj/root/root-6.20.04-install/lib/libPhysics.so;/home/prithivraj/root/root-6.20.04-install/lib/libMathCore.so;/home/prithivraj/root/root-6.20.04-install/lib/libThread.so;/home/prithivraj/root/root-6.20.04-install/lib/libMultiProc.so;/home/prithivraj/root/root-6.20.04-install/lib/libRooStats.so;/home/prithivraj/root/root-6.20.04-install/lib/libRooFit.so;/home/prithivraj/root/root-6.20.04-install/lib/libRooFitCore.so;/home/prithivraj/root/root-6.20.04-install/lib/libTreePlayer.so;/home/prithivraj/root/root-6.20.04-install/lib/libGeom.so;/bin/sh: 1: GEANT4_CONFIG_EXECUTABLE-NOTFOUND: not found
-- Reconstruction ...
-- pbuilder: will build library <Reconstruction>
-- programs: ReconstructionApp
-- project libraries( exe): ND280Event;EffStudy;Reconstruction
-- external libraries: /home/prithivraj/root/root-6.20.04-install/lib/libCore.so;/home/prithivraj/root/root-6.20.04-install/lib/libRIO.so;/home/prithivraj/root/root-6.20.04-install/lib/libNet.so;/home/prithivraj/root/root-6.20.04-install/lib/libHist.so;/home/prithivraj/root/root-6.20.04-install/lib/libGraf.so;/home/prithivraj/root/root-6.20.04-install/lib/libGraf3d.so;/home/prithivraj/root/root-6.20.04-install/lib/libGpad.so;/home/prithivraj/root/root-6.20.04-install/lib/libTree.so;/home/prithivraj/root/root-6.20.04-install/lib/libRint.so;/home/prithivraj/root/root-6.20.04-install/lib/libPostscript.so;/home/prithivraj/root/root-6.20.04-install/lib/libMatrix.so;/home/prithivraj/root/root-6.20.04-install/lib/libPhysics.so;/home/prithivraj/root/root-6.20.04-install/lib/libMathCore.so;/home/prithivraj/root/root-6.20.04-install/lib/libThread.so;/home/prithivraj/root/root-6.20.04-install/lib/libMultiProc.so;/home/prithivraj/root/root-6.20.04-install/lib/libRooStats.so;/home/prithivraj/root/root-6.20.04-install/lib/libRooFit.so;/home/prithivraj/root/root-6.20.04-install/lib/libRooFitCore.so;/home/prithivraj/root/root-6.20.04-install/lib/libTreePlayer.so;/home/prithivraj/root/root-6.20.04-install/lib/libGeom.so;/bin/sh: 1: GEANT4_CONFIG_EXECUTABLE-NOTFOUND: not found
-- pbuilder: will build the following executables: ReconstructionApp
-- ND280Event;EffStudy;Reconstruction /home/prithivraj/root/root-6.20.04-install/lib/libCore.so;/home/prithivraj/root/root-6.20.04-install/lib/libRIO.so;/home/prithivraj/root/root-6.20.04-install/lib/libNet.so;/home/prithivraj/root/root-6.20.04-install/lib/libHist.so;/home/prithivraj/root/root-6.20.04-install/lib/libGraf.so;/home/prithivraj/root/root-6.20.04-install/lib/libGraf3d.so;/home/prithivraj/root/root-6.20.04-install/lib/libGpad.so;/home/prithivraj/root/root-6.20.04-install/lib/libTree.so;/home/prithivraj/root/root-6.20.04-install/lib/libRint.so;/home/prithivraj/root/root-6.20.04-install/lib/libPostscript.so;/home/prithivraj/root/root-6.20.04-install/lib/libMatrix.so;/home/prithivraj/root/root-6.20.04-install/lib/libPhysics.so;/home/prithivraj/root/root-6.20.04-install/lib/libMathCore.so;/home/prithivraj/root/root-6.20.04-install/lib/libThread.so;/home/prithivraj/root/root-6.20.04-install/lib/libMultiProc.so;/home/prithivraj/root/root-6.20.04-install/lib/libRooStats.so;/home/prithivraj/root/root-6.20.04-install/lib/libRooFit.so;/home/prithivraj/root/root-6.20.04-install/lib/libRooFitCore.so;/home/prithivraj/root/root-6.20.04-install/lib/libTreePlayer.so;/home/prithivraj/root/root-6.20.04-install/lib/libGeom.so;/bin/sh: 1: GEANT4_CONFIG_EXECUTABLE-NOTFOUND: not found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/prithivraj/t2k-nd280-upgrade-master/src/build_dir
***********************************************************************************
Can you **mention your directories** @suvorov21 for the following command so that I can insert the correct installation directories? Thanks in advance....

export GEANT4_DIR=
export CLHEP_DIR=
export CMT_DIR=
export ROOT_DIR=

**Comment by suvorov21** [comment]
I see the problematic part here
```
-- libraries : /bin/sh: 1: GEANT4_CONFIG_EXECUTABLE-NOTFOUND: not found
-- flags : /bin/sh: 1: GEANT4_CONFIG_EXECUTABLE-NOTFOUND: not found
```
Libs and flags should be parsed properly. They are missed probably because of the not found `geant-config` executable, located in the $GEANT4_INSTALL_BIN.

Concerning the paths, everything is specified in the `env_setup.sh` file that should be sourced before the installation. I guess it was not done, thus the `geant-config` was not found during the configuration

**Comment by prithiv0005** [comment]
> 

I have tried all the methods. At T2KND280Up_CLHEP.sh file I specifed the 4 correct paths at the beginning of the file. This is as follows

> export GEANT4_DIR="$HOME:/geant4/geant4_v10.5/geant4.10.05.p01-install"
> export CLHEP_DIR="$HOME:/CLHEP/2.4.5.1/CLHEP-install"
> export CMT_DIR=$HOME:/CMT/CMT/v1r25p20160527/mgr
> export ROOT_DIR="$HOME:/root/root-6.20.04-install"

and for GEANT4_INSTALL_BIN, I wrote
> export GEANT4_INSTALL_BIN=$GEANT4_DIR/bin/

for first **cmake ../src** in the build directory my cmake successfully read the libraries and flags. I have given the same for your reference.

> prithivraj@prithiv:~/t2k-nd280-upgrade-master/build$ cmake ../src
-- /home/prithivraj/t2k-nd280-upgrade-master/src/../cmake
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
 Looking for Geant4...
GEANT4_INCLUDE_DIRS : /home/prithivraj/geant4/geant4_v10.5/geant4.10.05.p01-install/include/Geant4
GEANT4_LIBRARY_DIR : /home/prithivraj/geant4/geant4_v10.5/geant4.10.05.p01-install/lib/Geant4-10.5.1/Linux-g++
GEANT4_CONFIG_EXECUTABLES : 
-- found in /home/prithivraj/geant4/geant4_v10.5/geant4.10.05.p01-install/include/Geant4
> -- **libraries** : -L/home/prithivraj/geant4/geant4_v10.5/geant4.10.05.p01-install/bin/../lib -lG4OpenGL -lG4gl2ps -lG4Tree -lG4FR -lG4GMocren -lG4visHepRep -lG4RayTracer -lG4VRML -lG4vis_management -lG4modeling -lG4interfaces -lG4persistency -lG4analysis -lG4error_propagation -lG4readout -lG4physicslists -lG4run -lG4event -lG4tracking -lG4parmodels -lG4processes -lG4digits_hits -lG4track -lG4particles -lG4geometry -lG4materials -lG4graphics_reps -lG4intercoms -lG4global -lG4clhep -lG4zlib
> -- **flags** : -DG4INTY_USE_XT -DG4VIS_USE_OPENGL -DG4UI_USE_TCSH -DG4INTY_USE_QT -DG4UI_USE_QT -DG4VIS_USE_OPENGLQT -I/usr/include/x86_64-linux-gnu/qt5/ -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/lib/x86_64-linux-gnu/qt5//mkspecs/linux-g++ -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -DG4VIS_USE_RAYTRACERX -W -Wall -pedantic -Wno-non-virtual-dtor -Wno-long-long -Wwrite-strings -Wpointer-arith -Woverloaded-virtual -Wno-variadic-macros -Wshadow -pipe -DG4USE_STD11 -pthread -ftls-model=initial-exec -std=c++11 -DG4MULTITHREADED -I/home/prithivraj/geant4/geant4_v10.5/geant4.10.05.p01-install/bin/../include/Geant4

but for second **cmake t2k-nd280-upgrade/src/**, I get
> prithivraj@prithiv:~/t2k-nd280-upgrade-master/src/build_dir$ cmake ..
-- /home/prithivraj/t2k-nd280-upgrade-master/src/../cmake
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Looking for Geant4...
GEANT4_INCLUDE_DIRS : /home/prithivraj/geant4/geant4_v10.5/geant4.10.05.p01-install/include/Geant4
GEANT4_LIBRARY_DIR : /home/prithivraj/geant4/geant4_v10.5/geant4.10.05.p01-install/lib/Geant4-10.5.1/Linux-g++
GEANT4_CONFIG_EXECUTABLES :
-- found in /home/prithivraj/geant4/geant4_v10.5/geant4.10.05.p01-install/include/Geant4
> -- **libraries** : /bin/sh: 1: GEANT4_CONFIG_EXECUTABLE-NOTFOUND: not found
> -- **flags** : /bin/sh: 1: GEANT4_CONFIG_EXECUTABLE-NOTFOUND: not found

**Comment by suvorov21** [comment]
Hey!
The `T2KND280Up_CLHEP` is some kind of legacy. `env_setup.sh` should b enough.
Why do you need 2 CMake runs? One should be sufficient. Since the first one was successful, I would proceed with `make` and I expect it to run smoothly.

**Comment by prithiv0005** [comment]
> Hey! The `T2KND280Up_CLHEP` is some kind of legacy. `env_setup.sh` should b enough. Why do you need 2 CMake runs? One should be sufficient. Since the first one was successful, I would proceed with `make` and I expect it to run smoothly.

Thank you so much for the clarification. Now I have executed the commands and analyzed the results successfully.
